version: '3.4'

services:
  front:
    image: node:14
    ports:
      - 8002:80/tcp
    # volumes:
    #   - ./front:/front
    command: bash -c "npm install @chrisoakman/chessboardjs body-parser express express-session express-ejs-layouts connect-flash passport passport-local cors ejs axios amqplib && git clone https://github.com/JunakDeemaz/MicroChess.git && cd MicroChess && git checkout experimental_k8s && node microservices/front/front.js"
    container_name: front
    networks: 
      - relations-1
    depends_on: 
      - users
      - matchmaking-queue
      - game-server

  users:
    image: node:14
    ports:
      - 9000:9000
    # volumes:
    #   - ./users:/users
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors mongoose && git clone https://github.com/JunakDeemaz/MicroChess.git && cd MicroChess && git checkout experimental_k8s && node microservices/users/users.js"
    depends_on:
      - users-db
    container_name: users

  users-db:
    image: mongo:latest
    # volumes:
    #   - ./data:/data/db
    ports: 
      - 27017:27017
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null
    container_name: users-db

  matchmaking-server:
    image: node:14
    ports:
      - 9001:9001
    # volumes:
    #   - ./matchmaking_server:/matchmaking_server
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors axios amqplib && git clone https://github.com/JunakDeemaz/MicroChess.git && cd MicroChess && git checkout experimental_k8s && node microservices/matchmaking_server/matchmaking.js"
    depends_on:
      - matchmaking-queue
    container_name: matchmaking-server

  matchmaking-queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - relations-1
    container_name: "matchmaking-queue"

  game-server:
    image: node:14
    ports:
      - 9002:9002
    # volumes:
    #   - ./game_server:/game_server
    command: bash -c "npm install chess.js body-parser express express-session express-ejs-layouts cors ejs axios amqplib && git clone https://github.com/JunakDeemaz/MicroChess.git && cd MicroChess && git checkout experimental_k8s && node microservices/game_server/game_server.js"
    container_name: game-server
    depends_on: 
      - match-history-queue
    networks: 
      - relations-1

  match-history:
    image: node:14
    ports:
      - 9003:9003
    # volumes:
    #   - ./match_history:/match_history
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors axios amqplib mongoose && git clone https://github.com/JunakDeemaz/MicroChess.git && cd MicroChess && git checkout experimental_k8s && node microservices/match_history/match_history.js"
    depends_on:
      - match-history-db
      - match-history-queue
    container_name: match-history

  match-history-queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - relations-1
    container_name: "match-history-queue"

  match-history-db:
    image: mongo:latest
    # volumes:
    #   - ./history_data:/data/db
    ports: 
      - 27018:27017
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null
    container_name: match-history-db

networks:
    relations-1: