version: '3.4'

services:
  front:
    image: front:latest
    build: ./front
    ports:
      - 8002:80/tcp
    container_name: front
    networks: 
      - relations-1
    depends_on: 
      - users
      - matchmaking-queue
      - game-server

  users:
    image: users:latest
    build: ./users
    ports:
      - 9000:9000
    container_name: users
    networks:
      - relations-1
    depends_on:
      - users-db

  users-db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
    container_name: users-db
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null

  matchmaking-server:
    image: matchmaking:latest
    build: ./matchmaking_server
    ports:
      - 9001:9001
    container_name: matchmaking-server
    networks:
      - relations-1
    depends_on:
      - matchmaking-queue

  matchmaking-queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672
    container_name: "matchmaking-queue"
    networks:
      - relations-1

  game-server:
    image: game-server:latest
    build: ./game_server
    ports:
      - 9002:9002
    container_name: game-server
    networks: 
      - relations-1
    depends_on: 
      - match-history-queue

  match-history:
    image: match-history:latest
    build: ./match_history
    ports:
      - 9003:9003
    container_name: match-history
    networks:
      - relations-1
    depends_on:
      - match-history-db
      - match-history-queue

  match-history-queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5673:5672
      - 15673:15672
    container_name: match-history-queue
    networks:
      - relations-1

  match-history-db:
    image: mongo:latest
    volumes:
      - ./history_data:/data/db
    ports: 
      - 27018:27017
    container_name: match-history-db
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null

networks:
    relations-1: