version: '3.4'

services:
  front:
    image: node:14
    ports:
      - 8002:80/tcp
    volumes:
      - ./front:/front
    build: ./front
    container_name: front
    depends_on: 
      - middle

  middle:
    image: node:14
    ports:
      - 9000:9000
    volumes:
      - ./middle:/middle
    networks:
      - relations-1
    build: ./middle
    depends_on:
      - redis
    container_name: middle

  redis:
    image: redis:4.0.2
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - relations-1
    command: bash -c 'redis-server'
    container_name: redis

networks:
    relations-1: