version: '3.4'

services:
  front:
    image: front:latest
    build: ./front
    ports:
      - 8002:80/tcp
    container_name: front
    networks: 
      - relations-1
    depends_on: 
      - users
      - matchmaking_queue
      - game_server

  users:
    image: users:latest
    build: ./users
    ports:
      - 9000:9000
    container_name: users
    networks:
      - relations-1
    depends_on:
      - users_db

  users_db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
    container_name: users_db
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null

  matchmaking_server:
    image: matchmaking:latest
    build: ./matchmaking_server
    ports:
      - 9001:9001
    container_name: matchmaking_server
    networks:
      - relations-1
    depends_on:
      - matchmaking_queue

  matchmaking_queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672
    container_name: "matchmaking_queue"
    networks:
      - relations-1

  game_server:
    image: game_server:latest
    build: ./game_server
    ports:
      - 9002:9002
    container_name: game_server
    networks: 
      - relations-1
    depends_on: 
      - match_history_queue

  match_history:
    image: match_history:latest
    build: ./match_history
    ports:
      - 9003:9003
    container_name: match_history
    networks:
      - relations-1
    depends_on:
      - match_history_db
      - match_history_queue

  match_history_queue:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5673:5672
      - 15673:15672
    container_name: match_history_queue
    networks:
      - relations-1

  match_history_db:
    image: mongo:latest
    volumes:
      - ./history_data:/data/db
    ports: 
      - 27018:27017
    container_name: match_history_db
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null

networks:
    relations-1: