version: '3.4'

services:
  front:
    image: node:14
    ports:
      - 8002:80/tcp
    volumes:
      - ./front:/front
    command: bash -c "npm install @chrisoakman/chessboardjs body-parser express express-session express-ejs-layouts connect-flash passport passport-local cors ejs axios && node front/front.js"
    container_name: front
    networks: 
      - relations-1
    depends_on: 
      - middle

  middle:
    image: node:14
    ports:
      - 9000:9000
    volumes:
      - ./middle:/middle
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors ioredis && node middle/middle.js"
    depends_on:
      - redis
    container_name: middle

  redis:
    image: redis:4.0.2
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - relations-1
    command: bash -c 'redis-server'
    container_name: redis

networks:
    relations-1: