version: '3.4'

services:
  front:
    image: node:14
    ports:
      - 8002:80/tcp
    volumes:
      - ./front:/front
    command: bash -c "npm install @chrisoakman/chessboardjs body-parser express express-session express-ejs-layouts connect-flash passport passport-local cors ejs axios && node front/front.js"
    container_name: front
    networks: 
      - relations-1
    depends_on: 
      - users

  users:
    image: node:14
    ports:
      - 9000:9000
    volumes:
      - ./users:/users
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors ioredis mongoose && node users/users.js"
    depends_on:
      - users_db
    container_name: users

  users_db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports: 
      - 27017:27017
    networks:
      - relations-1
    command: mongod --quiet --logpath /dev/null
    container_name: users_db

networks:
    relations-1: