version: '3.4'

services:
  middle:
    image: node:14
    ports:
      - 9000:9000
    volumes:
      - ./middle:/middle
    networks:
      - relations-1
    command: bash -c "npm install body-parser express cors ioredis && node middle/middle.js"
    depends_on:
      - redis
    container_name: middle

  redis:
    image: redis:4.0.2
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - relations-1
    command: bash -c 'redis-server'
    container_name: redis

  front:
    container_name: front
    image: node:14
    restart: always
    build: ./front
    ports:
      - "7500:7500"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null

networks:
    relations-1: